import type { Metadata } from "next";
import "./ui/globals.css";
import { Space_Mono } from "next/font/google";

const spaceMono = Space_Mono({ weight: ["400"], subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nasa Astronomic Images Interface",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>{children}</body>
    </html>
  );
}
